# Generated by Django 3.1.4 on 2020-12-09 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201209_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='name',
            field=models.CharField(help_text='What is your specification (e.g. Medical Doctor)', max_length=200),
        ),
    ]
