# Generated by Django 3.1.4 on 2020-12-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201209_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='specification',
        ),
        migrations.AddField(
            model_name='doctor',
            name='specification',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='users.Specification'),
        ),
    ]
