# Generated by Django 3.1.4 on 2020-12-09 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email')),
                ('time_of_appointment', models.DateTimeField()),
                ('date', models.DateField()),
                ('who_to_see', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('A', 'Approved'), ('C', 'Canceled'), ('P', 'Pending')], default='m', help_text='Book availability', max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
