# Generated by Django 3.1.4 on 2020-12-09 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201209_1527'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentinstance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor'),
        ),
        migrations.AlterField(
            model_name='createappointment',
            name='who_to_see',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.doctor'),
        ),
    ]
