# Generated by Django 3.1.4 on 2020-12-10 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('record', '0002_auto_20201209_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentinstance',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.createappointment'),
        ),
        migrations.AlterField(
            model_name='appointmentinstance',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointmentinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('A', 'Approved'), ('C', 'Canceled'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
