# Generated by Django 3.1.4 on 2020-12-10 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_auto_20201210_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='createappointment',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.appointmentinstance'),
        ),
    ]
