# Generated by Django 3.1.4 on 2020-12-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_createappointment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createappointment',
            name='status',
        ),
        migrations.AlterField(
            model_name='createappointment',
            name='time_of_appointment',
            field=models.TimeField(),
        ),
    ]
