# Generated by Django 3.1.4 on 2020-12-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_auto_20201211_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('canceled', 'Canceled'), ('pending', 'Pending')], default='P', max_length=20),
        ),
    ]
