# Generated by Django 3.1.4 on 2020-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_auto_20201211_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Psending', max_length=20),
        ),
    ]
