# Generated by Django 3.1.4 on 2020-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_auto_20201211_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('Approved', 'Approved'), ('Canceled', 'Canceled'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='createappointment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
    ]
