# Generated by Django 3.1.4 on 2020-12-12 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_auto_20201211_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='createappointment',
            name='status',
            field=models.ForeignKey(blank=True, default='Pending', null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.appointmentinstance'),
        ),
        migrations.AlterField(
            model_name='appointmentinstance',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.createappointment'),
        ),
    ]
