# Generated by Django 3.1.4 on 2020-12-12 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0012_auto_20201212_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createappointment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='record.appointmentinstance'),
        ),
    ]
